### ISSUE TITLE
Feature - Log X-Forwarded-For header if present

### ISSUE THREAD

**Issue by j-martin** [OpenAS2/OpenAs2App#182]
We are using OpenAS2 behind a load balancer. It works well, but unfortunately, the client IP is always the IP of our load balancer. It would be very useful is if, in addition to log the client IP, OpenAS2 would also log `X-Forwarded-For` which would allow us to see the actual IP of the client.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by VboxNick** [comment]
Hi @j-martin,

Which load balancer do you use? Could you please share your config?

Thanks.

**Comment by j-martin** [comment]
@VboxNick 

We are using a standard GKE (Google Kubernetes Engine) / Kubernetes Load Balancer. https://cloud.google.com/load-balancing/docs/network
As far as config, there's not much since GKE does most of the magic in the background.

Part of our helm chart:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "as2.fullname" . }}
  labels:
    {{- include "as2.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.portHttp }}
      targetPort: {{ .Values.portHttp }}
      protocol: TCP
      name: http
    - port: {{ .Values.portHttps }}
      targetPort: {{ .Values.portHttps }}
      protocol: TCP
      name: https
  selector:
    {{- include "as2.selectorLabels" . | nindent 4 }}

```

... and we are using raw TCP for Loadbalancing so there will never be an `X-Forwarded-For` header. AND the logic for the header is here: https://github.com/OpenAS2/OpenAs2App/blob/1e0d7aad3ec62c478b634d29dc18d0dd132cdd07/Server/src/main/java/org/openas2/message/BaseMessage.java

Sorry for this unnecessary issue. Closing now.
